### ISSUE TITLE
TypeError: arr.forEach is not a function

### ISSUE THREAD

**Issue by dimensi** [jsumners/node-activedirectory#33]
When I try to call 
```
getGroupMembershipForUser({
  attributes: { group: ['cn', 'dn' ] },
}, 'user')
```

I got error 

```
UnhandledPromiseRejectionWarning: TypeError: arr.forEach is not a function
    at Array.from.forEach (/Users/dimensi/projects/digital-horizon-space/server/node_modules/activedirectory2/lib/components/utilities.js:254:9)
    at Array.forEach (<anonymous>)
    at Object.joinAttributes (/Users/dimensi/projects/digital-horizon-space/server/node_modules/activedirectory2/lib/components/utilities.js:253:25)
    at PromisedAD.gdns [as getDistinguishedNames] (/Users/dimensi/projects/digital-horizon-space/server/node_modules/activedirectory2/lib/activedirectory.js:326:25)
    at promise (/Users/dimensi/projects/digital-horizon-space/server/node_modules/activedirectory2/lib/adpromise.js:14:26)
    at new Promise (<anonymous>)
    at promiseWrapper (/Users/dimensi/projects/digital-horizon-space/server/node_modules/activedirectory2/lib/adpromise.js:17:10)
    at PromisedAD.gdn [as getDistinguishedNames] (/Users/dimensi/projects/digital-horizon-space/server/node_modules/activedirectory2/lib/adpromise.js:84:10)
    at PromisedAD.gudn [as getUserDistinguishedName] (/Users/dimensi/projects/digital-horizon-space/server/node_modules/activedirectory2/lib/activedirectory.js:373:8)
    at PromisedAD.gudn [as getUserDistinguishedName] (/Users/dimensi/projects/digital-horizon-space/server/node_modules/activedirectory2/lib/adpromise.js:125:48)
```

But if i call like that
```
getGroupMembershipForUser({
        attributes: ['cn', 'dn'],
      }, 'user')
```
no problem.

**Comment by jsumners** [comment]
So what is your question?

**Comment by dimensi** [comment]
i think no question. I bad reading your doc.
