### ISSUE TITLE
error when using promisify (from util) with ad.authenticate?

### ISSUE THREAD

**Issue by LeonardoVini** [jsumners/node-activedirectory#54]
I am using this lib to authenticate, look for the group, name and email of the user who is trying to access my application, but I am getting a weird error when trying to use promisify.

![image](https://user-images.githubusercontent.com/37921663/67034582-4dd1f980-f0ee-11e9-8877-92fe825d5a07.png)

`TypeError: Cannot read property 'url' of undefined
    at Object.createClient (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\node_modules\activedirectory2\lib\components\utilities.js:19:26)
    at authenticate (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\node_modules\activedirectory2\lib\activedirectory.js:933:24)
    at Promise (internal/util.js:274:30)
    at new Promise (<anonymous>)
    at authenticate (internal/util.js:273:12)
    at authenticationDAO.authentication (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\app\models\authenticationDAO.js:27:60)
    at Object.module.exports.authentication (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\app\controllers\authentication.js:20:21)
    at C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\app\routes\authentication.js:3:46
    at Layer.handle [as handle_request] (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\node_modules\express\lib\router\route.js:137:13)
TypeError: Cannot read property 'url' of undefined
    at Object.createClient (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\node_modules\activedirectory2\lib\components\utilities.js:19:26)
    at authenticate (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\node_modules\activedirectory2\lib\activedirectory.js:933:24)
    at Promise (internal/util.js:274:30)
    at new Promise (<anonymous>)
    at authenticate (internal/util.js:273:12)
    at authenticationDAO.authentication (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\app\models\authenticationDAO.js:27:60)
    at Object.module.exports.authentication (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\app\controllers\authentication.js:20:21)
    at C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\backend\app\routes\authentication.js:3:46
    at Layer.handle [as handle_request] (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\leooliveira\Downloads\00 - Projetos Equinix\First Pricing System\Price-List\node_modules\express\lib\router\route.js:137:13)`

**Comment by jsumners** [comment]
At the very least you would need to `promisify(ad.authenticate.bind(ad))`. But I would not be surprised if `ad.authenticate` just doesn't work with `util.promisify`. 

I would suggest using `const AD = require('activedirectory/lib/adpromise')`.

https://github.com/jsumners/node-activedirectory/blob/9f0d92be752d782de3b05ae2620a4bb9c3c4118c/lib/adpromise.js#L19-L50

**Comment by LeonardoVini** [comment]
Can you help me?

How would you do to authenticate and authorize (using the groups to which the user belongs) a user in AD?

Currently I use the ad.authenticate function and within it I use the ad.findUser function. In the function of finding the user I take the opportunity to search all the groups to which he belongs.
Below is the code.

CONTROLLER
```
module.exports.authentication = function (application, req, res) {

  let credentials = req.body

  let user = credentials.login + '@mycompany.com'
  let pass = credentials.senha

  // var cookie = require('cookie-signature');
  var ActiveDirectory = require('activedirectory2');
  var config = {
    url: 'ldap://global.mycompany.com',
    baseDN: 'dc=global,dc=mycompany,dc=com',
    username: 'svc-srpuser@mycompany.com',
    password: 'srp@mycompany2019'
  }
  var ad = new ActiveDirectory(config);

  let authorization_level = [
    { ldap_group: 'br-soldev-ad', permission: 'FULL' },
    { ldap_group: 'GSE-Brazil', permission: 'FULL' },
    { ldap_group: 'comercialsp', permission: 'MIDDLE' },
    { ldap_group: 'comercialrj', permission: 'MIDDLE' },
    { ldap_group: 'br-qss-om', permission: 'BASIC' },
    { ldap_group: 'br-eti', permission: 'BASIC' },
    { ldap_group: 'equipe.csm', permission: 'BASIC' }
  ];

  let opts = {
    includeMembership: ['all']
  };

  var authenticationDAO = new application.app.models.authenticationDAO();

  authenticationDAO.authentication(ad, authorization_level, opts, user, pass, res);
}
```

MODEL
```
function authenticationDAO() { }

authenticationDAO.prototype.authentication = (ad, authorization_level, opts, user, pass, res) => {

  ad.authenticate(user, pass, function (err, auth) {

    if (err) {
      return res.send({ message: 'Usuário e/ou senha incorretos', error: true })
    }

    if (!auth) {
      return res.send({ message: 'Usuário e/ou senha incorretos', error: true })
    }

    ad.findUser(opts, user, function (err, user) {
      if (err) {
        return res.send({ message: 'Usuário e/ou senha incorretos', error: true })
      }

      if (user.groups.length === 0) {
        return res.send({ message: 'Não foi possível verificar a quais grupos do AD você pertence', error: true })
      }

      let username = user.cn
      let email = user.mail
      let groups = [...user.groups.map(group => group.cn)]
      let auth_infos = []

      for (let i = 0; i < authorization_level.length; i++) {
        for (let j = 0; j < groups.length; j++) {
          if (authorization_level[i].ldap_group === groups[j]) {
            auth_infos.push({ ldap_group: groups[j], permission: authorization_level[i].permission })
          }
        }
      }

      if (auth_infos.length === 0) {
        return res.send({ message: 'Você não possui autorização para utilizar essa ferramenta', error: true })
      }

      return res.send({ auth, username, email, ldap_group: auth_infos[0].ldap_group, permission: auth_infos[0].permission, error: false })
    })
  })
}

module.exports = function () {
  return authenticationDAO;
}

```
My error occurs when the function fetches user information.
