### ISSUE TITLE
Find Users ERROR

### ISSUE THREAD

**Issue by DardoJav** [jsumners/node-activedirectory#90]
Hi All, 

I'm getting an ERROR trying to run the findUsers() to get more than 500 users
When I run he app for the first time it gives me all the users, but in the next calls it return with an error: 
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1532:19)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'XX.XXX.XX.XXX',
  port: XXX,
  localAddress: undefined
}

this is the code part:

`const AD = require('activedirectory2').promiseWrapper
    const config = { url: 'ldaps://XX.XXX.XX.XXX:XXX',
      baseDN: 'DC=NEXTGEN,DC=LOCAL',
      username: 'dardo.juan.j.luna',
      password: 'password',
    }
    const ad = new AD(config)

    var opts = {
      scope: 'sub',
      filter: '(&(objectCategory=User)(objectCategory=Person))', 
    }
    
    const results = await ad.findUsers(opts, true)`

Don't know what I'm doing wrong here
Please help
Thanks!

**Comment by jurjendijkstra** [comment]
I don't think ad.findUsers needs two parameters. Can you try ad.findUsers(opts) instead (opts, true) ?
