### ISSUE TITLE
Error: Callback was already called

### ISSUE THREAD

**Issue by rajsolanki73** [jsumners/node-activedirectory#92]
Randomly i m getting following error.

at node_modules/activedirectory2/node_modules/async/dist/async.js:318:36
    at GroupMembersForDN [as callback] (/node_modules/activedirectory2/lib/components/getGroupMembershipForDN.js:47:16)

i m using 

ad.getGroupMembershipForUser(username, function(err, role) {}

**Comment by jsumners** [comment]
Without a way to reproduce it we cannot assist.

**Comment by rajsolanki73** [comment]
thanks. Let me explain in detail. 

this is my code snippet.

`ad.getGroupMembershipForUser(username, function(err, role) {

    if (err) {
      

      logger.info("getUserRole_error" + username,  err);
      return;
    }
   
    if (! role) 
    {
      

      logger.log("getUserRole_error",  "User: " + sAMAccountName + " not found.");
    } 
    else 
    {
    //logger.log("info",  "User: " + username + " found.");
    return callback(err,role);
    }
  });`

So my this AD API gets around 50 to 60K requests in an hour and in a randomly i get above error and my nodejs app crashes. I do use PM2 so process does start back up but it crashes in randomly. before crash i always see following error.

Error: Callback was already called.
    at /home/myapi/node_modules/activedirectory2/node_modules/async/dist/async.js:318:36
    at GroupMembersForDN [as callback] (/home/myapi/node_modules/activedirectory2/lib/components/getGroupMembershipForDN.js:47:16)
    at Searcher.search [as callback] (/home/myapi/node_modules/activedirectory2/lib/components/getGroupMembershipForDN.js:113:12)
    at Client.Searcher.client.on (/home/myapi/node_modules/activedirectory2/lib/components/search.js:67:10)
    at Client.emit (events.js:198:13)
    at Backoff.<anonymous> (/home/myapi/node_modules/ldapjs/lib/client/client.js:1036:12)
    at Backoff.emit (events.js:198:13)
    at Backoff.backoff (/home/myapi/node_modules/backoff/lib/backoff.js:41:14)
    at /home/myapi/node_modules/ldapjs/lib/client/client.js:1020:15
    at f (/home/myapi/node_modules/once/once.js:25:25)
    at f (/home/myapi/node_modules/once/once.js:25:25)
    at /home/myapi/node_modules/ldapjs/lib/client/client.js:945:7
    at next (/home/myapi/node_modules/vasync/lib/vasync.js:843:6)
    at /home/myapi/node_modules/ldapjs/lib/client/client.js:162:9
    at callbackWrapper (/home/myapi/node_modules/ldapjs/lib/client/client.js:292:5)
    at sendResult (/home/myapi/node_modules/ldapjs/lib/client/client.js:1193:37)
    at messageCallback (/home/myapi/node_modules/ldapjs/lib/client/client.js:1216:18)
    at Parser.onMessage (/home/myapi/node_modules/ldapjs/lib/client/client.js:884:14)
    at Parser.emit (events.js:198:13)
    at Parser.write (/home/myapi/node_modules/ldapjs/lib/messages/parser.js:107:8)
    at Socket.onData (/home/myapi/node_modules/ldapjs/lib/client/client.js:871:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)

Please let me know what more details i can provide.

**Comment by davidrapin** [comment]
We had the same issue, the worse being that the error is not reported correctly and generates an uncaught error which crashes the library.
So far, our strategy is to fork the library and implement a warning instead of a hard crash when this happens by wrapping the callback in a function that prevents multiple calls and warns.

**Comment by gmasclet** [comment]
I suspect this comes from the [Searcher](https://github.com/jsumners/node-activedirectory/blob/194dda33531df6863c9e7e66bcddf65e9035a602/lib/components/search.js) class.

This class performs searches agains an AD server, using a `ldap.js` client. It listens to `error` events emitted by the client:

https://github.com/jsumners/node-activedirectory/blob/194dda33531df6863c9e7e66bcddf65e9035a602/lib/components/search.js#L65-L68

But also to `error` and `end` events emitted by the search result:

https://github.com/jsumners/node-activedirectory/blob/194dda33531df6863c9e7e66bcddf65e9035a602/lib/components/search.js#L146-L151

When an error happens, looks like events from both the client and the search result are emitted, causing `this.callback` to be called twice (as it is indirectly called by `errCallback` and `onSearchEnd`).

**Comment by jsumners** [comment]
Are you providing a PR to address this issue? Please remember to include unit tests.

**Comment by gmasclet** [comment]
hello @jsumners. We've merged a PR addressing this issue in our fork of node-activedirectory (see https://github.com/Linkurious/node-activedirectory2/pull/4). I can provide a PR backporting it in this repository, so that everyone benefits from it. 

Note this issue happens when a socket emit an error event (as far as we understand). We have experienced it sporadically in production, but we haven't been able to reproduce it consistently in a development environment. As such, I won't be able to provide complete unit tests. Yet, I can unit test the `callOnlyOnce()` utility function.

Let me know what you think.

**Comment by jsumners** [comment]
Looking at `onSearchEnd`, it seems that function never does anything with any parameters passed to it. So a more appropriate solution may be that the `end` handler should invoke the `errCallback` if `err` is set before invoking `onSearchEnd`.

**Comment by jsumners** [comment]
What I can say is that this code is quite old and I am sure I would approach the whole thing much differently if I started writing it today. In particular, I would structure things for actual unit testing. That said, I am open to whatever approach solve the problem.

As for how to test any solution, I would create a new test suite that injects a mock object to the `Searcher` which has a `client` that generates a client error. Something like (does not work, it is just an outline):

```js
const mockquire = require('mock-require')
mockquire('../path/to/utilities.js', {
  createClient () {
    return {
      // all necessary methods, including:
      search(...params) {
        this.emit('error', Error('bad client error'))
      }
    }
  }
})

const searchFactory = require('../path/to/search.js')

tap.test('new test', async t => {
  const searcher = searchFactory({ url: 'ldap://example.com' })

  // perform the search and look for the client error making sure
  // only one error is received for one search.
})
```

Note: detecting the errors can get complicated and I would imagine it could look something like the test found at https://github.com/ldapjs/node-ldapjs/blob/e2d516f6bb95f60de103e5c6fb812b8522f09134/test/issue-890.test.js

**Comment by jsumners** [comment]
Why aren't you able to participate in the upstream project?

**Comment by jurjendijkstra** [comment]
In project node-ldapjs you mean? 

Well, perhaps I am able to do that, but I had three thoughts:

1. I thought it made sense to add my comment here, because here is where the "Callback was already called" issue was reported and investigated. 
2. I dont know how to make a unit test to validate my change, so you'd probably not accept the change anyway?
3. and I am trying to figure out if I can catch the error in my application code, which depends on activedirectroy2, not depends directly on ldapjs, so I thought this is the place to search

**Comment by jurjendijkstra** [comment]
I just find github confusing with forks and pull requests. I am an old man still using subversion :-) 
What should I do if you think the snippet I posted is ok?

**Comment by jsumners** [comment]
> 2\. I dont know how to make a unit test to validate my change, so you'd probably not accept the change anyway?

A unit test for such a change will definitely be difficult. I suspect it would look something like https://github.com/ldapjs/node-ldapjs/blob/6ceef130145b38ba33b5ccc798bf49304194fb0f/test/issue-890.test.js. The code in that project is so difficult that if there is a _really good_ reason, and we notate it correctly, then I am willing to consider not having a test to cover it. But we really need to exhaust efforts to get code coverage first.

> I just find github confusing with forks and pull requests. I am an old man still using subversion :-)

At least in the projects I participated in, a willingness to learn is welcomed and questions will be answered. I would suggest starting by reading https://jrfom.com/posts/2017/03/08/a-primer-on-contributing-to-projects-with-git/.

**Comment by jurjendijkstra** [comment]
Thanks!! 

I start reading 

For me I think it is best when I first begin by editing that "if" statement directly in the node_modules/ldapjs code at our customer, who's operation is blocked by this problem. See if it is indeed the fix for their problem.

**Comment by Drilmo** [comment]
hi 😃 have you any update for this bug ?

**Comment by jurjendijkstra** [comment]
@Drilmo  what works for me is maybe not the solution for you, but you can temporarily try to add a dependency to my temporary fork of ldapjs version 2:
"ldapjs": "github:jurjendijkstra/vanmeijel-ldapjs#v2.x"
But only to see if it helps. I will not keep or maintain that fork, it is just temporary.

**Comment by Drilmo** [comment]
> @Drilmo what works for me is maybe not the solution for you, but you can temporarily try to add a dependency to my temporary fork of ldapjs version 2: "ldapjs": "github:jurjendijkstra/vanmeijel-ldapjs#v2.x" But only to see if it helps. I will not keep or maintain that fork, it is just temporary.

@jurjendijkstra Thks for your answer 😄 I have this error when i use your fork : 


```
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'abstract-logging'
Require stack:
- C:\Users\xx\Git\xxx\vanmeijel-ldapjs-2.x\lib\logger.js
- C:\Users\xx\Git\xxx\vanmeijel-ldapjs-2.x\lib\index.js
- C:\Users\xx\Git\xxx\node_modules\.pnpm\activedirectory2@2.2.0\node_modules\activedirectory2\lib\activedirectory.js
- C:\Users\xx\Git\xxx\node_modules\.pnpm\activedirectory2@2.2.0\node_modules\activedirectory2\index.js
- C:\Users\xx\Git\xxx\dist\libs\activeDirectory.js
- C:\Users\xx\Git\xxx\dist\checkBitbucket.js
- C:\Users\xx\Git\xxx\dist\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\xx\Git\xxx\vanmeijel-ldapjs-2.x\lib\logger.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\xx\\Git\\xxx\\vanmeijel-ldapjs-2.x\\lib\\logger.js',
    'C:\\Users\\xx\\Git\\xxx\\vanmeijel-ldapjs-2.x\\lib\\index.js',
    'C:\\Users\\xx\\Git\\xxx\\node_modules\\.pnpm\\activedirectory2@2.2.0\\node_modules\\activedirectory2\\lib\\activedirectory.js',
    'C:\\Users\\xx\\Git\\xxx\\node_modules\\.pnpm\\activedirectory2@2.2.0\\node_modules\\activedirectory2\\index.js',
    'C:\\Users\\xx\\Git\\xxx\\dist\\libs\\activeDirectory.js',
    'C:\\Users\\xx\\Git\\xxx\\dist\\checkBitbucket.js',
    'C:\\Users\\xx\\Git\\xxx\\dist\\index.js'
  ]
}
```

**Comment by davidrapin** [comment]
Hi, we’ve created a fork of this repository that:
- adds support for nested groups
- fixes the “callback called twice” error (it’s a workaround but we use it in production)
- adds some unit tests for both these improvements

We did not take the time to contribute our code back into this repo yet, but feel free to take a look and merge back any of our changes: https://github.com/Linkurious/node-activedirectory2

**Comment by davidrapin** [comment]
@jsumners i suppose you marked my previous comment as “off topic” (I cannot see who did), but it is not clear to me why. I did literally provide a link our fork that fixes the very bug that is the topic of this discussion.

**Comment by Drilmo** [comment]
> Hi, we’ve created a fork of this repository that:
> 
> * adds support for nested groups
> * fixes the “callback called twice” error (it’s a workaround but we use it in production, and found it to be reliable)
> * adds some unit tests for both these improvements
> 
> We did not take the time to contribute our code back into this repo yet, but feel free to take a look and merge back any of our changes: https://github.com/Linkurious/node-activedirectory2

Hi @davidrapin, your fork resolve the "Error: Callback was already called" 😃

**Comment by davidrapin** [comment]
@Drilmo yes, it does. See for yourself.
